name: kzn
description: A new learning mobile application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # image slider
  carousel_slider: ^4.0.0
  # serialization
  json_annotation: ^4.4.0
  # state management
  provider: ^6.0.0
  # http api
  # http: ^0.12.2
  dio: ^4.0.0
  # shared preferences
  shared_preferences: ^2.0.5
  # intro slider
  intro_slider: ^2.3.3
  # rating bar
  flutter_rating_bar: ^4.0.0
  # sweet alert
  sweetalert: ^0.0.1
  # search bar
  flutter_search_bar: ^2.1.0
  # webview
  webview_flutter: ^2.0.4
  # open facebook
  url_launcher: ^6.0.3
  # loading modal
  modal_progress_hud: ^0.1.3
  # video player
  better_player: ^0.0.70
  font_awesome_flutter: ^9.2.0
  change_app_package_name: ^1.0.0
  http: ^0.13.4
  flutter_html: ^2.0.0
  firebase_messaging: ^11.2.3
  firebase_core: ^1.10.5
  flutter_local_notifications: ^9.1.4
  path_provider: ^2.0.9
  flutter_inappwebview: ^5.3.2
  introduction_screen:
  visibility_detector: ^0.2.2
  cloud_functions: ^3.2.8
  auto_orientation: ^2.2.1
  analyzer: ^3.3.1
  get: ^4.6.1
  cloud_firestore: ^3.1.9
  firebase_storage: ^10.2.8
  uuid: ^3.0.6
  dartz: ^0.10.1
  cloud_firestore_platform_interface: ^5.5.0
  firebase_storage_platform_interface: ^4.1.0
  fwfh_text_style: ^2.7.3+1
  flutter_launcher_icons: ^0.9.3

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  build_runner: ^2.1.8
  json_serializable: ^6.1.5
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/images/logo.jpg"
  android: true
  ios: true
  remove_alpha_ios: true



flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/images/slider/
